#!/usr/bin/env bun
// Merge NN-slide-*.png files in a directory into a 16:9 PPTX.
// Usage: bun run merge-to-pptx.ts <slide-deck-dir>
//
// Lookup order per slide N:
//   1. NN-slide-{slug}.png       (composited — preferred, has all text)
//   2. NN-slide-{slug}-bg.png    (background only — fallback if compose-text not run)

import { readdirSync, existsSync, renameSync } from "node:fs";
import { join, basename, resolve } from "node:path";
import pptxgen from "pptxgenjs";

const arg = process.argv[2];
if (!arg) {
  console.error("Usage: bun run merge-to-pptx.ts <slide-deck-dir>");
  process.exit(1);
}

const dir = resolve(arg);
if (!existsSync(dir)) {
  console.error(`Directory not found: ${dir}`);
  process.exit(1);
}

const slug = basename(dir.replace(/\/$/, ""));

// Collect slide files. For each NN-slide-{slug}, prefer composited over -bg.
const all = readdirSync(dir);
const seen = new Map<string, string>(); // NN-slide-slug → chosen filename
for (const f of all) {
  const composited = f.match(/^(\d{2}-slide-[^.]+)\.png$/);
  if (composited && !f.includes("-bg")) {
    seen.set(composited[1], f);
  }
}
// Fallback: -bg.png when no composited version exists
for (const f of all) {
  const bg = f.match(/^(\d{2}-slide-[^.]+)-bg\.png$/);
  if (bg && !seen.has(bg[1])) {
    seen.set(bg[1], f);
  }
}

const files = Array.from(seen.entries())
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([, f]) => f);

if (files.length === 0) {
  console.error(`No NN-slide-*.png files found in ${dir}`);
  process.exit(1);
}

const outPath = join(dir, `${slug}.pptx`);

if (existsSync(outPath)) {
  const ts = new Date()
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d+Z$/, "")
    .replace("T", "-");
  const backup = join(dir, `${slug}-backup-${ts}.pptx`);
  renameSync(outPath, backup);
  console.log(`Backed up existing PPTX → ${backup}`);
}

const pptx = new pptxgen();
pptx.layout = "LAYOUT_WIDE"; // 13.33" x 7.5" = 16:9
pptx.title = slug;
pptx.subject = "Generated by dialog_skill_deck";

for (const file of files) {
  const slide = pptx.addSlide();
  slide.background = { color: "FFFFFF" };
  slide.addImage({
    path: join(dir, file),
    x: 0,
    y: 0,
    w: "100%",
    h: "100%",
    sizing: { type: "contain", w: "100%", h: "100%" } as any,
  });
}

await pptx.writeFile({ fileName: outPath });
console.log(`Created ${outPath} (${files.length} slides)`);
console.log(`Note: text is baked into slide images. Native editable text boxes planned for v0.3.0.`);
