#!/usr/bin/env bun
// Merge NN-slide-*.png files in a directory into a 16:9 PDF.
// Usage: bun run merge-to-pdf.ts <slide-deck-dir>

import { readdirSync, readFileSync, writeFileSync, existsSync, renameSync } from "node:fs";
import { join, basename, resolve } from "node:path";
import { PDFDocument } from "pdf-lib";

const arg = process.argv[2];
if (!arg) {
  console.error("Usage: bun run merge-to-pdf.ts <slide-deck-dir>");
  process.exit(1);
}

const dir = resolve(arg);
if (!existsSync(dir)) {
  console.error(`Directory not found: ${dir}`);
  process.exit(1);
}

const slug = basename(dir.replace(/\/$/, ""));
const slidePattern = /^\d{2}-slide-.+\.png$/;
const files = readdirSync(dir).filter((f) => slidePattern.test(f)).sort();

if (files.length === 0) {
  console.error(`No NN-slide-*.png files found in ${dir}`);
  process.exit(1);
}

const outPath = join(dir, `${slug}.pdf`);

if (existsSync(outPath)) {
  const ts = new Date()
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d+Z$/, "")
    .replace("T", "-");
  const backup = join(dir, `${slug}-backup-${ts}.pdf`);
  renameSync(outPath, backup);
  console.log(`Backed up existing PDF → ${backup}`);
}

const pdf = await PDFDocument.create();
pdf.setTitle(slug);
pdf.setSubject("Generated by dialog_skill_deck");

// 16:9 page size in points (PDF default unit). 960 x 540 pt ≈ 13.33" x 7.5".
const pageWidth = 960;
const pageHeight = 540;
const pageAspect = pageWidth / pageHeight;

for (const file of files) {
  const imgBytes = readFileSync(join(dir, file));
  const img = await pdf.embedPng(imgBytes);

  const imgAspect = img.width / img.height;
  let drawWidth: number;
  let drawHeight: number;
  if (imgAspect > pageAspect) {
    drawWidth = pageWidth;
    drawHeight = pageWidth / imgAspect;
  } else {
    drawHeight = pageHeight;
    drawWidth = pageHeight * imgAspect;
  }
  const x = (pageWidth - drawWidth) / 2;
  const y = (pageHeight - drawHeight) / 2;

  const page = pdf.addPage([pageWidth, pageHeight]);
  page.drawImage(img, { x, y, width: drawWidth, height: drawHeight });
}

const outBytes = await pdf.save();
writeFileSync(outPath, outBytes);
console.log(`Created ${outPath} (${files.length} pages)`);
