#!/usr/bin/env bun
// Merge NN-slide-*.png files in a directory into a 16:9 PPTX.
// Usage: bun run merge-to-pptx.ts <slide-deck-dir>

import { readdirSync, existsSync, renameSync } from "node:fs";
import { join, basename, resolve } from "node:path";
import pptxgen from "pptxgenjs";

const arg = process.argv[2];
if (!arg) {
  console.error("Usage: bun run merge-to-pptx.ts <slide-deck-dir>");
  process.exit(1);
}

const dir = resolve(arg);
if (!existsSync(dir)) {
  console.error(`Directory not found: ${dir}`);
  process.exit(1);
}

const slug = basename(dir.replace(/\/$/, ""));
const slidePattern = /^\d{2}-slide-.+\.png$/;
const files = readdirSync(dir).filter((f) => slidePattern.test(f)).sort();

if (files.length === 0) {
  console.error(`No NN-slide-*.png files found in ${dir}`);
  process.exit(1);
}

const outPath = join(dir, `${slug}.pptx`);

// Backup existing file
if (existsSync(outPath)) {
  const ts = new Date()
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d+Z$/, "")
    .replace("T", "-");
  const backup = join(dir, `${slug}-backup-${ts}.pptx`);
  renameSync(outPath, backup);
  console.log(`Backed up existing PPTX → ${backup}`);
}

const pptx = new pptxgen();
pptx.layout = "LAYOUT_WIDE"; // 13.33" x 7.5" = 16:9
pptx.title = slug;
pptx.subject = "Generated by dialog_skill_deck";

for (const file of files) {
  const slide = pptx.addSlide();
  slide.background = { color: "FFFFFF" };
  slide.addImage({
    path: join(dir, file),
    x: 0,
    y: 0,
    w: "100%",
    h: "100%",
    sizing: { type: "contain", w: "100%", h: "100%" } as any,
  });
}

await pptx.writeFile({ fileName: outPath });
console.log(`Created ${outPath} (${files.length} slides)`);
